#!/bin/sh

if [ -z $SKUAPSO_CONFIG_DIR ]; then
	SKUAPSO_CONFIG_DIR="./etc"
fi

CONFIG=""

for i in $(ls $SKUAPSO_CONFIG_DIR/*.config); do
  CONFIG="$CONFIG -config $i"
done

echo "$CONFIG"

erl -pa ebin -pa lib/*/ebin $CONFIG -args_file $SKUAPSO_CONFIG_DIR/vm.args
